models/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask_login import LoginManager
from utils.db import db

login = LoginManager()

#extructura de la base de datos
#tabla de login

class logindb(UserMixin,db.Model):
    
    __tablename__ = 'users'

    id= db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(100))
    email= db.Column(db.String(100),unique=True)
    password= db.Column(db.String(102), nullable=False)


#genera la contrasena

    def set_password(self,password):
        return generate_password_hash(password)

    def check_password(self,password_hash,password):
        return check_password_hash(password_hash,password) 
        
#carga el usuario

@login.user_loader
def load_user(id):
    return logindb.query.get(int(id))


#tabla de estudiantes usados en el crud
class student(db.Model):

    __tablename__ = 'student'
    id= db.Column(db.Integer,primary_key=True)
    nombre =db.Column(db.String(50))
    correo = db.Column(db.String(100))
    telefono = db.Column(db.Integer)
    fecha_de_cumpleanos =db.Column(db.Date())

    def __init__(self,nombre,correo,telefono,fecha_de_cumpleanos):
        self.nombre = nombre
        self.correo = correo
        self.telefono =telefono
        self.fecha_de_cumpleanos = fecha_de_cumpleanos
        





   

app.py
from ctypes import create_unicode_buffer
from pickle import TRUE
from flask import Flask, render_template,redirect
from routes.login import user_login
from routes.crud import crud
from flask_sqlalchemy import SQLAlchemy



app = Flask(__name__)

app.secret_key = 'S==%TxpO@E3@zA'

app.register_blueprint(user_login)
app.register_blueprint(crud)


app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://bitcode:poiuy0mn@bitcode.mysql.pythonanywhere-services.com/bitcode$crud'
app.config['SQLALCHEMY_POOL_SIZE'] = 100
app.config['SQLALCHEMY_POOL_RECYCLE'] = 290
app.config[' SQLALCHEMY_TRACK_MODIFICATIONS'] = False



SQLAlchemy(app)

@app.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

@app.errorhandler(500)
def internal_error(error):

    return redirect('/login')

routes/crud.py
from crypt import methods
import imp
from flask import Blueprint,render_template,redirect,url_for,request,flash
from flask_login import login_required
from models.models import student
from static.forms import AddForm, UpdateForm
from utils.db import db


crud = Blueprint('crud',__name__)

#ruta del crud
@crud.route('/crud')
@login_required
def home_crud():
    students = student.query.all()
    return render_template('crud.html',students = students)

#ruta de add
@crud.route('/add', methods=['POST','GET'])
@login_required
def add():

    form = AddForm()

    if form.validate_on_submit():
        try:
            if request.method == 'POST':
                nombre = request.form['nombre']
                correo = request.form['correo']
                telefono = request.form['telefono']
                fecha_de_cumpleanos = request.form['fecha']
                students= student(nombre=nombre,correo=correo,telefono=telefono,fecha_de_cumpleanos=fecha_de_cumpleanos)
                db.session.add(students)
                db.session.commit()

                flash('Agregado correctamente')

                return redirect(url_for('crud.home_crud'))

            else:

                return render_template('add.html',form = form)
        except:
            db.session.rollback()

    return render_template('add.html',form = form)

#ruta de update
@crud.route('/update/<id>', methods=['POST','GET'])
@login_required
def update(id):
    updateid = student.query.get(id)
    form = UpdateForm()

    if form.validate_on_submit():
        try:
            if request.method == 'POST':
                updateid.nombre = request.form['nombre']
                updateid.correo = request.form['correo']
                updateid.telefono = request.form['telefono']
                updateid.fecha_de_cumpleanos = request.form['fecha']
                db.session.commit()

                flash('Modificado correctamente')

                return redirect(url_for('crud.home_crud'))
            else:
                return render_template('update.html',updateid = updateid,form = form)

        except:
            db.session.rollback()

    return render_template('update.html',updateid = updateid,form = form)

#ruta de delete
@crud.route('/delete/<id>')
@login_required
def delete(id):
    deleteid =  student.query.get(id)
    db.session.delete(deleteid)
    db.session.commit()
    flash('Borrado correctamente')
    return redirect(url_for('crud.home_crud'))



#ruta de about
@crud.route('/about')
@login_required
def about():
   return render_template('about.html')

routes/login.py
from werkzeug.security import generate_password_hash
from crypt import methods
from click import password_option
from flask import Blueprint,render_template,request,redirect, url_for,flash
from models.models import logindb
from flask_login import current_user, login_required, login_user, logout_user
from static.forms import SignupForm, LoginForm
from utils.db import db

user_login = Blueprint('user_login', __name__)

#ruta raiz
@user_login.route('/')
def index ():
    return redirect(url_for('user_login.login'))

#ruta login
@user_login.route('/login',methods=['GET','POST'])
def login():
    sing_up= 'sing_up'
    rout = '/register'
    login = 'No tienes cuenta?'
    form = LoginForm()


    if current_user.is_authenticated:
        return redirect('/crud')

    if form.validate_on_submit():
        try:
            if request.method == "POST":
                email = request.form['email']
                user = logindb.query.filter_by(email = email).first()
            if user is not None and user.check_password(user.password,request.form['password']):
                login_user(user)
                return redirect('/crud')
        except:
            db.session.rollback()


    return render_template('login.html', sing_up = sing_up , rout = rout,login = login, form = form )

#ruta register


@user_login.route('/register', methods = ['GET','POST'])
def register():
    sing_up = 'Iniciar Sesión'
    rout = '/login'
    login = 'Tienes cuenta?'
    form = SignupForm()

    if form.validate_on_submit():

        try:

            if current_user.is_authenticated:
                return redirect('/')

            if request.method == 'POST':
                username = request.form['username']
                email = request.form['email']
                password = request.form['password']


                if logindb.query.filter_by(email=email).first():
                    flash('Correo ya existente')
                    return redirect('/register')


                hash = generate_password_hash(password)
                user = logindb(username=username,email=email,password=hash)
                db.session.add(user)
                db.session.commit()
                flash(' Registrado correctamente ')
                return redirect('/login')

        except:
            db.session.rollback()

    return render_template('register.html',sing_up = sing_up,rout = rout,login = login, form = form)

#ruta de logout
@user_login.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user_login.login'))

templates/about.html
{%extends 'layout.html'%}
{% block content%}


  <div class="card">
      <img class="img" src="https://u.ph.edim.co/dd0b/164235582_4_140.png">
      
    <div class="card-body">
      <h5 class="card-title">Moises Perez</h5>
      <p class="card-text">Cedula: 29.671.315<br>
          Sección: 2
      </p>

        <p ><small >Estudiante...</small></p> 
        <a ></a>
      
      
    </div>
     
    </div>
{%endblock%}

templates/add.html
{%extends 'layout.html'%}
{% block content%}
<div class="forms">
       <h1 class="inf">Agregar informacion</h1>
       <form class="forms-1" action="/add" method="POST">

           {{ form.hidden_tag() }}
           {{ form.nombre(class_ = 'form') }}
            {% for error in form.nombre.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}

            {{ form.correo(class_ = 'form') }}
            {% for error in form.correo.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}

            {{ form.telefono(class_ = 'form') }}
            {% for error in form.telefono.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}
            {{ form.fecha(class_ = 'form') }}
            {% for error in form.fecha.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}

            {{ form.submit(class_ = 'botons') }}


       </form>
  </div>
{%endblock%}

templates/crud.html
{%extends 'layout.html'%}


{% block content%}



<div class="contain">
  <ul class="table-option">
    <li>
  Estudiantes
    </li>
    <li>
      <a class="link0" href="/add">Agregar</a>
    </li>

  </ul>

  {% with messages = get_flashed_messages() %}

  {% if messages%}
      {% for message in messages%}
       <h4>{{message}}</h4>
      {% endfor %}
  {% endif%}

  {% endwith %}

      <table class="table">
          <thead class="table0" >
            <tr >
              <th  scope="col">Nombre</th>
              <th  scope="col">Correo</th>
              <th  scope="col">Telefono</th>
              <th  scope="col">N id</th>
              <th  scope="col"> Fecha de cumpleaños</th>

            </tr>
          </thead>

      {% for students in students%}


        <tbody>
          <tr>
            <th scope="row">{{students.nombre}}</th>
             <td>{{students.correo}}</td>
             <td>{{students.telefono}}</td>
             <td>{{students.id}}</td>
             <td>{{students.fecha_de_cumpleanos}} </td>

             <td><a class="link1" href="{{url_for('crud.update',id = students.id)}}">update</a></td>
             <td><a class="link2" href="{{url_for('crud.delete',id= students.id)}}">borrar</a></td>

          </tr>



      {%endfor%}
  </table>



</div>



{%endblock%}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static',filename='css/dashboard.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400&display=swap" rel="stylesheet">
    <link  rel="icon"   href="https://img.icons8.com/color/344/javascript--v1.png" type="image/png" />
    
    <title>CRUD</title>
</head>
<body>
    
    {%include('partials/_navbar.html')%}
    {% block content%}
    {%endblock%}

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link  rel="icon"   href="https://img.icons8.com/color/344/javascript--v1.png" type="image/png" />
    <title>Login</title>

</head>
<body >
    {%include('partials/_navbar_login_form.html')%}


       {% with messages = get_flashed_messages() %}

            {% if messages%}
                {% for message in messages%}
                <div class="notif">
                    <span class="notiff-type">{{message}}</span>
                </div>

                 {% endfor %}
            {% endif%}

          {% endwith %}

    <div class="login">

        <h1 class="welcome">Welcome</h1>
        <h2 class="welcome_2">Introduce tus credenciales</h2>
        <div class="line">
            <span class="line1"></span>
            <svg class="lock" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="2em" height="2em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 32 32"><g fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M5 15v15h22V15Zm4 0C9 9 9 5 16 5s7 4 7 10m-7 5v3"/><circle cx="16" cy="24" r="1"/></g></svg>
            <span class="line2"></span>

        </div>



        <form action="/login" method="POST">

            {{ form.hidden_tag() }}
            {{ form.email(class_ = 'form') }}

            {% for error in form.email.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}

            {{ form.password(class_ = 'form') }}

            {% for error in form.password.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}

            <input class="checkbox" type="checkbox" name="recordar-password" >
            <h2 class="checkbox1"> Recordar password </h2>
            <a href="#"><h2 class="checkbox2"> recuperar password </h2> </a>

            {{ form.submit(class_ = 'botons') }}


        </form>
    </div>



</body>
</html>

templates/partials/_navbar.html
<div class="navs">
    <div class="navs1">
        <ul class="logo">
            <li>
                <a href="/">
                    <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="3em" height="3em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 32 32"><path fill="#0F54BB
                        " d="m26.297 27.031l.031-.063a.746.746 0 0 0 .073-.156v-.005c.099-.26.12-.536.073-.813v.01a2.368 2.368 0 0 0-.313-.828l.01.01l-7.094-12.474l-1.083-1.891l-8.156 14.365c-.141.25-.229.521-.276.802v.016c-.057.323-.021.651.109.953l-.005-.01c.016.047.042.089.068.135l-.005-.005c.214.365.667.802 1.667.802h13.198c.208 0 1.234-.042 1.708-.849zm-8.302-12.422l6.479 11.396H11.521zm13.666 10.579L22.307 8.709c-.099-.177-.635-1.052-1.578-1.052c-.422 0-1.026.182-1.521 1.047L18 10.824l1.073 1.896l1.667-2.953l9.255 16.245h-3.521c.047.271.021.547-.073.807v-.01c-.021.057-.042.115-.073.167v-.005l-.031.063c-.474.807-1.495.849-1.693.849h5.505c.203 0 1.219-.042 1.693-.849c.214-.37.359-.984-.141-1.844zM9.74 27.078l-.063-.125v-.005a1.668 1.668 0 0 1-.115-.953v.01H1.999l11.24-19.776l3.687 6.484l1.073-1.891l-3.219-5.667c-.089-.161-.63-1.036-1.568-1.036c-.422 0-1.031.182-1.521 1.052L.306 25.187c-.099.172-.568 1.078-.099 1.885c.214.37.667.802 1.667.802h9.531c-.99 0-1.453-.427-1.667-.802z"/></svg>
                </a>
            </li>
            <li class="crud">
               <a  class="crud-a" href="/"> CRUD</a>
            </li>
        </ul>


        <ul class="options">
            <li><a href="/" class="links"><svg class="icons1" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path class="icons1" d="M20.42 10.18L12.71 2.3C12.617 2.20627 12.5064 2.13188 12.3846 2.08111C12.2627 2.03034 12.132 2.0042 12 2.0042C11.868 2.0042 11.7373 2.03034 11.6154 2.08111C11.4936 2.13188 11.383 2.20627 11.29 2.3L3.57999 10.19C3.39343 10.3781 3.24609 10.6013 3.14652 10.8468C3.04695 11.0923 2.99715 11.3551 2.99999 11.62V20C2.99922 20.5119 3.19477 21.0046 3.54637 21.3767C3.89797 21.7488 4.37885 21.9718 4.88999 22H19.11C19.6211 21.9718 20.102 21.7488 20.4536 21.3767C20.8052 21.0046 21.0008 20.5119 21 20V11.62C21.0008 11.0829 20.7928 10.5666 20.42 10.18V10.18Z" fill="#8B8B8B"/>
                <path d="M10 20V14H14V20H10ZM19 20H16V13C16 12.7348 15.8946 12.4804 15.7071 12.2929C15.5196 12.1054 15.2652 12 15 12H9C8.73478 12 8.48043 12.1054 8.29289 12.2929C8.10536 12.4804 8 12.7348 8 13V20H5V11.58L12 4.43L19 11.62V20Z" fill="white"/>
                </svg>
                Inicio</a></li>
            <li><a href="/about" class="links"><svg class="icons1" width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path class="icons1" d="M19.3 7.8394C19.69 7.8394 20 7.5294 20 7.1394V6.20938C20 2.10938 18.75 0.859383 14.65 0.859383H5.35C1.25 0.859373 0 2.10938 0 6.20938V6.67938C0 7.0694 0.31 7.3794 0.7 7.3794C1.6 7.3794 2.33 8.1094 2.33 9.0094C2.33 9.9094 1.6 10.6294 0.7 10.6294C0.31 10.6294 0 10.9394 0 11.3294V11.7994C0 15.8994 1.25 17.1494 5.35 17.1494H14.65C18.75 17.1494 20 15.8994 20 11.7994C20 11.4094 19.69 11.0994 19.3 11.0994C18.4 11.0994 17.67 10.3694 17.67 9.4694C17.67 8.5694 18.4 7.8394 19.3 7.8394ZM7 5.87938C7.55 5.87938 8 6.32938 8 6.87938C8 7.4294 7.56 7.8794 7 7.8794C6.45 7.8794 6 7.4294 6 6.87938C6 6.32938 6.44 5.87938 7 5.87938ZM13 12.8794C12.44 12.8794 11.99 12.4294 11.99 11.8794C11.99 11.3294 12.44 10.8794 12.99 10.8794C13.54 10.8794 13.99 11.3294 13.99 11.8794C13.99 12.4294 13.56 12.8794 13 12.8794ZM13.9 6.47937L7.17 13.2094C7.02 13.3594 6.83 13.4294 6.64 13.4294C6.45 13.4294 6.26 13.3594 6.11 13.2094C5.82 12.9194 5.82 12.4394 6.11 12.1494L12.84 5.41938C13.13 5.12938 13.61 5.12938 13.9 5.41938C14.19 5.70938 14.19 6.18937 13.9 6.47937Z" fill="#2B00D4"/>
                </svg>
                Acerca de</a></li>

            <li><a href="/logout" class="links"><svg  class="icons1" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path  d="M19 21H5C4.46957 21 3.96086 20.7893 3.58579 20.4142C3.21071 20.0391 3 19.5304 3 19V15H5V19H19V5H5V9H3V5C3 4.46957 3.21071 3.96086 3.58579 3.58579C3.96086 3.21071 4.46957 3 5 3H19C19.5304 3 20.0391 3.21071 20.4142 3.58579C20.7893 3.96086 21 4.46957 21 5V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21ZM11 16V13H3V11H11V8L16 12L11 16Z" fill="#8B8B8B"/>
                </svg>
                Salir</a></li>

        </ul>
        </div>

        <div class="navs2">
        <ul class="li0">
            <li class="li1">
                Welcome Back
            </li>
            <li class="li2">
                Hola {{ current_user.username }}, Buenos dias!
            </li>
        </ul>
        <div class="search">
            <form action="/search" method="POST">
                <input class="search2" type="text" name="search" placeholder="Buscar">
                <button class="search3" type="submit"><svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M18.3333 18.3333L16.6667 16.6667M9.58333 17.5C13.9556 17.5 17.5 13.9556 17.5 9.58332C17.5 5.21107 13.9556 1.66666 9.58333 1.66666C5.21107 1.66666 1.66666 5.21107 1.66666 9.58332C1.66666 13.9556 5.21107 17.5 9.58333 17.5Z" stroke="#9A9A9A" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    </button>



            </form>

        </div>

        <div class="icons2">

            <a href="#" class="icons3"><svg class="icons4" width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.2 20.82C9.66 21.43 10.31 21.78 11 21.78C11.69 21.78 12.34 21.43 12.8 20.82L14.3 18.82C14.35 18.76 14.42 18.72 14.5 18.72H15C19.42 18.72 21.75 16.39 21.75 11.97V6.97C21.75 2.55 19.42 0.220001 15 0.220001H7C2.58 0.220001 0.25 2.55 0.25 6.97V11.97C0.25 17.59 2.83 18.72 7 18.72H7.5C7.55 18.73 7.67 18.78 7.7 18.82L9.2 20.82ZM1.75 6.97C1.75 3.39 3.42 1.72 7 1.72H15C18.58 1.72 20.25 3.39 20.25 6.97V11.97C20.25 15.55 18.58 17.22 15 17.22H14.5C13.95 17.22 13.43 17.48 13.1 17.92L11.6 19.92C11.25 20.38 10.75 20.38 10.4 19.92L8.9 17.92C8.59 17.51 8.01 17.22 7.5 17.22H7C3.3 17.22 1.75 16.49 1.75 11.97V6.97ZM10 9.97C10 10.52 10.44 10.97 11 10.97C11.56 10.97 12 10.52 12 9.97C12 9.42 11.55 8.97 11 8.97C10.45 8.97 10 9.42 10 9.97ZM14 9.97C14 10.52 14.44 10.97 15 10.97C15.56 10.97 16 10.52 16 9.97C16 9.42 15.55 8.97 15 8.97C14.45 8.97 14 9.42 14 9.97ZM6 9.97C6 10.52 6.44 10.97 7 10.97C7.56 10.97 8 10.52 8 9.97C8 9.42 7.55 8.97 7 8.97C6.45 8.97 6 9.42 6 9.97Z" fill="#626266"/>
            </svg>
            </a>
             <a href="#"  class="icons3">
            <svg class="icons4" width="18" height="22" viewBox="0 0 18 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M3.77466 7.81494C3.77466 5.47173 5.31613 3.48313 7.4387 2.80952C8.17973 2.60227 8.97791 2.54373 9.82147 2.64918L9.82425 2.64952C10.0716 2.67951 10.3161 2.72954 10.5586 2.79524C12.7031 3.45598 14.2747 5.4621 14.2747 7.81494V10.7049C14.2747 11.1001 14.3561 11.5556 14.4689 11.967C14.582 12.3793 14.743 12.8068 14.9351 13.1397L14.9349 13.1398L14.9422 13.1518L16.0916 15.0608L16.0919 15.0613C16.5056 15.7517 16.17 16.6446 15.4193 16.8928L15.417 16.8936C13.6913 17.4702 11.909 17.8073 10.1172 17.905H7.92214C6.13083 17.8074 4.34909 17.4704 2.62377 16.8941C2.167 16.7391 1.90417 16.4539 1.79424 16.157C1.68456 15.8608 1.69833 15.4755 1.94719 15.0618L1.9473 15.0616L3.09719 13.1518L3.09719 13.1518L3.09887 13.149C3.29916 12.813 3.46387 12.3825 3.57858 11.9693C3.69324 11.5563 3.77466 11.1003 3.77466 10.7049V7.81494ZM5.18696 19.0931C4.16126 18.9088 3.14531 18.6498 2.147 18.3163L2.14421 18.3153C1.30181 18.0302 0.670049 17.4407 0.38758 16.6779C0.104784 15.9141 0.200986 15.0545 0.662023 14.2883L0.662136 14.2881L1.81045 12.3809L1.81121 12.3796C1.92071 12.1955 2.04067 11.9016 2.13324 11.5681C2.22609 11.2336 2.27466 10.9196 2.27466 10.7049V7.81494C2.27466 4.93333 4.08617 2.46987 6.63107 1.50265C7.09854 0.661241 7.9962 0.0949707 9.0245 0.0949707C10.0541 0.0949707 10.9528 0.662719 11.4197 1.50594C13.9598 2.47693 15.7747 4.94315 15.7747 7.81494V10.7049C15.7747 10.9198 15.8233 11.2343 15.9155 11.5703C16.0065 11.9023 16.1241 12.1973 16.2312 12.3847L17.3772 14.2881L17.3778 14.2891C18.2834 15.7983 17.5595 17.7644 15.8912 18.3167C14.8833 18.6534 13.8574 18.914 12.8216 19.0987C12.3108 20.7204 10.7893 21.905 9.00456 21.905C7.91122 21.905 6.89789 21.4517 6.17791 20.7317C5.72865 20.2824 5.38323 19.719 5.18696 19.0931Z" fill="#626266"/>
                </svg>

                </a>
            <img class="img1" src="https://icones.pro/wp-content/uploads/2021/02/icone-utilisateur-gris.png">

        </div>
    </div>

</div>

templates/partials/_navbar_login_form.html
<nav>

    <ul class="logo">
        <li>
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="2em" height="2em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 32 32"><path fill="#0fa958" d="m26.297 27.031l.031-.063a.746.746 0 0 0 .073-.156v-.005c.099-.26.12-.536.073-.813v.01a2.368 2.368 0 0 0-.313-.828l.01.01l-7.094-12.474l-1.083-1.891l-8.156 14.365c-.141.25-.229.521-.276.802v.016c-.057.323-.021.651.109.953l-.005-.01c.016.047.042.089.068.135l-.005-.005c.214.365.667.802 1.667.802h13.198c.208 0 1.234-.042 1.708-.849zm-8.302-12.422l6.479 11.396H11.521zm13.666 10.579L22.307 8.709c-.099-.177-.635-1.052-1.578-1.052c-.422 0-1.026.182-1.521 1.047L18 10.824l1.073 1.896l1.667-2.953l9.255 16.245h-3.521c.047.271.021.547-.073.807v-.01c-.021.057-.042.115-.073.167v-.005l-.031.063c-.474.807-1.495.849-1.693.849h5.505c.203 0 1.219-.042 1.693-.849c.214-.37.359-.984-.141-1.844zM9.74 27.078l-.063-.125v-.005a1.668 1.668 0 0 1-.115-.953v.01H1.999l11.24-19.776l3.687 6.484l1.073-1.891l-3.219-5.667c-.089-.161-.63-1.036-1.568-1.036c-.422 0-1.031.182-1.521 1.052L.306 25.187c-.099.172-.568 1.078-.099 1.885c.214.37.667.802 1.667.802h9.531c-.99 0-1.453-.427-1.667-.802z"/></svg>
            </a>
        </li>
        <li class="crud">
            CRUD
        </li>
    </ul>
    <ul class="count">
        <li>{{login}}?</li>
        <li>
            <a href="{{rout}}?" class="register">
                {{sing_up}}?
                </a>

        </li>


    </ul>
</nav>

templates/update.html
 {%extends 'layout.html'%}
 {% block content%}
 <div class="forms">
        <h1 class="inf">Actualizar informacion</h1>
        <form class="forms-1" action="/update/{{updateid.id}}" method="POST">

            {{ form.hidden_tag() }}
            <label>{{updateid.nombre}}</label>
            {{ form.nombre(class_ = 'form') }}
            {% for error in form.nombre.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}
            <label>{{updateid.correo}}</label>
            {{ form.correo(class_ = 'form') }}
            {% for error in form.correo.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}
            <label>{{updateid.telefono}}</label>
            {{ form.telefono(class_ = 'form') }}
            {% for error in form.telefono.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}
            <label>{{updateid.fecha_de_cumpleanos}}</label>
            {{ form.fecha(class_ = 'form') }}
            {% for error in form.fecha.errors %}
                <span style = "color:red">{{error}}</span>
            {%endfor%}

            {{ form.submit(class_ = 'botons') }}


        </form>
   </div>
{%endblock%}